name: CI 

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  unit_test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.13.0  

    
    - name: Build
      run: zig build --summary all
    
    - name: Run tests
      run: zig build test --summary all
    
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tabulate
    
    - name: Run size script
      run: python size.py

