name: CI 

on:
  push:

jobs:
  zig_unit_test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Zig
      uses: mlugg/setup-zig@v1 
      with:
        version: 0.14.0  

    
    - name: Build
      run: zig build --summary all
    
    - name: Run tests
      run: zig build test --summary all
    
  python_size_script: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tabulate
    
      - name: Run size script
        run: python size.py

  infra_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install zig 
        uses: mlugg/setup-zig@v1 
        with:
          version: 0.14.0  

      - name: Add Zig to system-wide PATH
        run: |
          sudo ln -s "$(which zig)" /usr/local/bin/zig
    
      - name: test hotswap_node.sh 
        run: |
          sudo ./scripts/bootstrap_node.sh 127.0.0.1 8080
          chmod +x scripts/hotswap_twnode.sh
          sudo ./scripts/hotswap_twnode.sh

  test_end_to_end:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install zig 
        uses: mlugg/setup-zig@v1 
        with:
          version: 0.14.0  

      - name: Add Zig to system-wide PATH
        run: sudo ln -s "$(which zig)" /usr/local/bin/zig

      - name: bootstrap tinyweather-node 
        run: sudo ./scripts/bootstrap_node.sh --address 127.0.0.1 --port 8080

      - name: bootstrap tinyweather-proxy
        run: sudo ./scripts/bootstrap_proxy.sh --address 127.0.0.1 --port 8081

      - name: bootstrap prometheus
        run: sudo ./scripts/bootstrap_prometheus.sh --prom-listen-address 127.0.0.1:9090 --proxy-address 127.0.0.1:8081 --node-address 127.0.0.1 --node-port 8080 --sensors "Temp,RainTotalAcc,Hum,Pres,Gas"

      - name: bootstrap grafana
        run: sudo ./scripts/bootstrap_grafana.sh

      - name: test curl end to end parallel small number 
        run: for i in {1..10}; do curl --parallel localhost:8081/metrics localhost:8081/metrics -H "Sensor:Temp"; done 

      - name: test curl end to end parallel large number 
        run: for i in {1..100}; do curl --parallel localhost:8081/metrics localhost:8081/metrics -H "Sensor:Temp"; done 

      - name: query prometheus server
        run: /opt/prometheus/promtool query instant http://localhost:9090 'Temp'

      - name: dump tinyweather-node logs
        run: journalctl -u tinyweather-node.service

      - name: dump tinyweather-proxy logs
        run: journalctl -u tinyweather-proxy.service

      - name: dump prometheus logs
        run: journalctl -u prometheus.service

      - name: test node still alive
        run: systemctl status tinyweather-node

      - name: test proxy still alive
        run: systemctl status tinyweather-proxy

      - name: test prometheus still alive
        run: systemctl status prometheus

      - name: test grafana still alive
        run: systemctl status grafana

