name: CI 

on:
  push:

jobs:
  zig_unit_test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Zig
      uses: mlugg/setup-zig@v1 
      with:
        version: 0.13.0  

    
    - name: Build
      run: zig build --summary all
    
    - name: Run tests
      run: zig build test --summary all
    
  python_size_script: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tabulate
    
      - name: Run size script
        run: python size.py

  run_local_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install zig 
        uses: mlugg/setup-zig@v1 
        with:
          version: 0.13.0  

      - name: Add Zig to system-wide PATH
        run: |
          sudo ln -s "$(which zig)" /usr/local/bin/zig

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
    
      - name: Run test_local 
        run: python test/test_local.py 
  install_prometheus:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Bootstrap prometheus
        run: |
          sudo ./scripts/bootstrap_prometheus.sh

  test_end_to_end:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install zig 
        uses: mlugg/setup-zig@v1 
        with:
          version: 0.13.0  

      - name: Add Zig to system-wide PATH
        run: |
          sudo ln -s "$(which zig)" /usr/local/bin/zig

      - name: bootstrap tinyweather-node 
        run: sudo ./scripts/bootstrap_node.sh

      - name: bootstrap tinyweather-proxy
        run: sudo ./scripts/bootstrap_proxy.sh

      # - name: start nginx service
      #   run: sudo systemctl start nginx
      #
      # - name: bootstrap nginx
      #   run: sudo ./scripts/bootstrap_nginx.sh

      - name: test curl end to end
        run: for i in {1..30}; do curl --parallel localhost:8082/metrics localhost:8082/metrics localhost:8083/metrics localhost:8083/metrics; done

      - name: dump tinyweather-node logs
        run: journalctl -u tinyweather-node.service

      - name: dump tinyweather-proxy logs
        run: journalctl -u tinyweather-proxy.service

      - name: test node still alive
        run: systemctl status tinyweather-node

      - name: test proxy still alive
        run: systemctl status tinyweather-proxy

      - name: test nginx still alive
        run: systemctl status nginx

      
