name: CI 

on:
  push:

jobs:
  zig_unit_test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Zig
      uses: mlugg/setup-zig@v1 
      with:
        version: 0.13.0  

    
    - name: Build
      run: zig build --summary all
    
    - name: Run tests
      run: zig build test --summary all
    
  python_size_script: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with: 
          version: '3.12.0'
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tabulate
    
      - name: Run size script
        run: python size.py
