name: CI 

on:
  push:

jobs:
  zig_unit_test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Zig
      uses: mlugg/setup-zig@v1 
      with:
        version: 0.13.0  

    
    - name: Build
      run: zig build --summary all
    
    - name: Run tests
      run: zig build test --summary all
    
  python_size_script: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tabulate
    
      - name: Run size script
        run: python size.py
  # build_and_install_prometheus:
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Set up Go
  #       uses: actions/setup-go@v5
  #       with:
  #         go-version: '1.21.0' 
  #
  #     - name: Set up node.js 
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 'latest'
  #
  #     - name: Verify installations
  #       run: |
  #         go version
  #         node --version
  #         npm --version
  #     - name: Bootstrap prometheus
  #       run: |
  #         sudo ./scripts/bootstrap_prometheus.sh

  test_end_to_end:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install zig 
        uses: mlugg/setup-zig@v1 
        with:
          version: 0.13.0  

      - name: Add Zig to system-wide PATH
        run: |
          sudo ln -s "$(which zig)" /usr/local/bin/zig

      - name: bootstrap tinyweather-node 
        run: sudo ./scripts/bootstrap_node.sh

      - name: bootstrap tinyweather-proxy
        run: sudo ./scripts/bootstrap_proxy.sh

      - name: test curl end to end
        run: curl -Z localhost:8081/metrics localhost:8081/metrics localhost:8081/metrics -H "sensor:Temp" -H "sensor:RainAcc"

      - name: test node still live
        run: systemctl status tinyweather-node

      - name: test proxy still alive
        run: systemctl status tinyweather-proxy
        

      

